version: '2.3'

services:
  gradle:
    image: quay.io/widen/builder-gradle:1.0.0
    environment:
      - BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_ARTIFACT_UPLOAD_DESTINATION
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_COMMIT
      - BUILDKITE_JOB_ID
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_TAG
      - CI
      - JFROG_USER
      - JFROG_PASS
      - GRADLE_SWITCHES
    volumes:
      - ./:/work
      - ~/.aws:/root/.aws
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
