name: NPM Security Check

on:
  pull_request:
    paths:
      - '**/package.json'
      - '**/yarn.lock'
      - '**/.yarnrc.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  npm-audit:
    uses: Widen/github-actions/.github/workflows/npm-security-check-workflow.yml@v1
    secrets: inherit
